/**
 * docs/SEEDS.md from the chain: every canonical seed record read back with
 * get_record (storage), plus the seed list and the hand checks in
 * docs/research/hand_checks.json.
 *   node tools/seeds_md.mjs
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { createRequire } from "node:module";
const root = new URL("..", import.meta.url).pathname;
const require = createRequire(new URL("../test/package.json", import.meta.url));
const { createClient } = require("genlayer-js");
const { studioDevnet } = require("genlayer-js/chains");
const client = createClient({ chain: studioDevnet });
const dep = JSON.parse(readFileSync(root + "deployments.json", "utf8"));
const addr = dep.contracts.AdminClaim.address;
const seeds = JSON.parse(readFileSync(root + "test/seeds.json", "utf8"));
const runs = JSON.parse(readFileSync(root + "docs/seed-canonical.json", "utf8")).runs;
const hand = existsSync(root + "docs/research/hand_checks.json") ? JSON.parse(readFileSync(root + "docs/research/hand_checks.json", "utf8")) : {};
const EX = "https://explorer-studio-dev.genlayer.com";
const norm = (v) => JSON.parse(JSON.stringify(v, (k, x) => (typeof x === "bigint" ? Number(x) : x instanceof Map ? Object.fromEntries(x) : x)));
async function view(fn, args) {
  for (let i = 0; i < 6; i++) {
    try { return norm(await client.readContract({ address: addr, functionName: fn, args })); }
    catch (e) { await new Promise((r) => setTimeout(r, 4000 * (i + 1))); }
  }
  throw new Error("view failed " + fn);
}
const iso = (t) => new Date(t * 1000).toISOString().replace("T", " ").slice(0, 16) + " UTC";
const day = (t) => new Date(t * 1000).toISOString().slice(0, 10);
const counts = {};
const rows = [];
const details = [];
for (const s of seeds) {
  const run = [...runs].reverse().find((r) => r.id === s.id && r.record_id);
  const tries = runs.filter((r) => r.id === s.id);
  if (!run) { rows.push(`| ${s.label} | ${s.chain} | - | - | not recorded (${tries.map((t) => t.revert || t.status).join("; ")}) |`); continue; }
  const r = await view("get_record", [run.record_id]);
  counts[r.verdict] = (counts[r.verdict] ?? 0) + 1;
  rows.push(`| ${s.label} | ${r.chain} | [#${r.record_id}](${EX}/tx/${run.tx}) | ${r.block} | **${r.verdict}** |`);
  const d = [];
  d.push(`### ${s.label} - record #${r.record_id}: ${r.verdict}`);
  d.push("");
  d.push(`* Docs: [${r.docs_repo}/${r.docs_path}](${r.docs_url}) at commit \`${r.commit}\` (${day(r.commit_date)}), branch proof: \`${r.branch}...${r.commit.slice(0, 10)}\` = ${r.branch_status}`);
  d.push(`* Docs sha256 \`${r.docs_sha256}\` (${r.docs_bytes} bytes)`);
  d.push(`* Chain: ${r.chain}, block ${r.block} (${iso(r.block_time)}), hash \`${r.block_hash}\``);
  d.push(`* Addresses: ${r.addresses.map((a) => "`" + a + "`").join(", ")}; subjects: ${r.subjects.map((a) => "`" + a + "`").join(", ")}`);
  d.push(`* Filing tx: [${run.tx}](${EX}/tx/${run.tx}), claims status ${r.claims_status}, basis ${r.basis}, evidence sha256 \`${r.evidence_sha256}\``);
  d.push("");
  d.push("Claims kept by code (quote = verbatim docs text):");
  d.push("");
  if (r.claims.kept.length === 0) d.push("_none_");
  else {
    d.push("| Field | Value (code's parse) | Quote | Result |");
    d.push("|---|---|---|---|");
    for (const k of r.claims.kept) d.push(`| ${k.field} | ${JSON.stringify(k.value)} | \`${k.quote.replace(/\|/g, "\\|").replace(/`/g, "'").slice(0, 160)}\` | ${k.result} |`);
  }
  if (r.claims.conflicts?.length) d.push(`\nConflicting fields (dropped): ${r.claims.conflicts.join(", ")}`);
  d.push("");
  d.push("Chain facts per hop:");
  d.push("");
  for (const [sub, ps] of Object.entries(r.paths)) for (const p of ps) d.push(`* ${p}`);
  const nodes = r.chain_facts.nodes;
  for (const [a, n] of Object.entries(nodes)) {
    if (n.kind === "SAFE") d.push(`  * \`${a}\`: Safe ${n.version} (singleton \`${n.singleton}\`), threshold ${n.threshold}, ${n.owners.length} owners, modules ${JSON.stringify(n.modules)}, guard \`${n.guard}\``);
    else d.push(`  * \`${a}\`: ${n.kind}${n.why ? " (" + n.why + ")" : ""}${n.delay !== undefined ? ", delay " + n.delay + " s" : ""}${n.admin ? ", admin `" + n.admin + "`" : ""}${n.owner ? ", owner `" + n.owner + "`" : ""}, code sha256 \`${n.code_sha256.slice(0, 16)}...\``);
  }
  d.push("");
  d.push(`> ${r.summary}`);
  if (hand[s.id]) { d.push(""); d.push(`**Checked by hand:** ${hand[s.id]}`); }
  d.push("");
  details.push(d.join("\n"));
}
const total = Object.values(counts).reduce((a, b) => a + b, 0);
const out = `# Seeds (canonical)

Real protocols' own docs, pinned to a commit, filed on the canonical deployment [\`${addr}\`](${EX}/address/${addr}) (6 h cooldown, block no older than 1 h). Nothing was forced: each row is what the contract recorded. Generated by \`tools/seeds_md.mjs\` from \`get_record\` (storage) and \`docs/seed-canonical.json\` (transactions).

Verdicts: ${Object.entries(counts).map(([k, v]) => `${k} ${v}`).join(" · ")} (${total} records, ${new Set(seeds.map((s) => s.chain)).size} chains).

| Protocol (docs) | Chain | Record | Block | Verdict |
|---|---|---|---|---|
${rows.join("\n")}

Labels are for reading this file only; the contract stores no protocol names, only \`github.com/<owner>/<repo>\`.

## Records

${details.join("\n")}`;
const demo = JSON.parse(readFileSync(root + "docs/seed-demo.json", "utf8")).steps;
const daddr = dep.contracts.AdminClaimDemo.address;
const demoMd = `

## Demo deployment: every path

Demo [\`${daddr}\`](${EX}/address/${daddr}) (60 s cooldown, block no older than 10 min, so Polygon only). Statements file: [docs/demo/claims.md](demo/claims.md) (this repo's own, see its header). Every transaction, in order (\`docs/seed-demo.json\`):

| Step | Expected | Got | Tx |
|---|---|---|---|
${demo.map((d) => `| ${d.step} | ${d.expect} | ${d.verdict ? "record #" + d.record_id + (d.prev_id ? " (prev #" + d.prev_id + ")" : "") + ": " + d.verdict : d.revert} ${d.matched ? "" : "(see note)"} | [${d.tx.slice(0, 10)}](${EX}/tx/${d.tx}) |`).join("\n")}

Notes: refusals are reverted transactions (nothing stored). \`GITHUB_API_HTTP_403\` rows are filings refused because the shared GitHub API budget was exhausted at that moment (a refusal, never a verdict). The "hard_to_read" paragraph came out MATCH: the model agreed on "three out of six" every time, so INCONCLUSIVE did not occur live (it is covered offline: \`test_unstable_model_is_inconclusive\`). A same-commit-same-block DUPLICATE cannot occur live: the cooldown (60 s) is longer than Polygon's finalized head ever stalls (it moves every few seconds); it is covered offline (\`test_a24_duplicate_filing\`).
`;
writeFileSync(root + "docs/SEEDS.md", out + demoMd);
console.log(Object.entries(counts), total);
